In [3]:
import numpy as np

A = ( np.random.randn(5,5) > 0 ) * 1
A

array([[0, 0, 0, 1, 1],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
B = np.nonzero(A)
B
#B = np.where(A == 0, np.nan, A)
#B


(array([0, 1, 1, 2, 2, 3, 4, 4], dtype=int64),
 array([3, 1, 3, 1, 3, 1, 0, 2], dtype=int64))

In [16]:
A = ( np.random.randn(5,5) > 0 ) * 1
A

array([[0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0]])

In [35]:
np.where(A >0, A, np.nan)

array([[nan, nan, nan,  1., nan],
       [nan,  1., nan,  1., nan],
       [nan,  1., nan,  1., nan],
       [nan,  1., nan, nan, nan],
       [ 1., nan,  1., nan, nan]])